MODELS = [
    # 'allinika',
    # 'bellamurr',
    # 'littleprincess199',
    # 'theperfectcpl',
    # 'vampirecollective',
    # 'no1syg',
    # 'sexyyennifer',
    # 'emma-modric',
    # 'dickforlily',
    # 'mysexymodel',
    # 'aryaholes',
    # 'behindthemaskk',
    # 'arrestme',
    # 'misslexa',
    # 'sweetie-fox',
    # 'mia-queen',
    # 'mynewprofession',
    # 'nini_divine',
    # 'booty_ass',
    # 'kisankanna',
    # 'hansel-grettel',
    # 'satanikweed',
    # 'divine_tits',
    # 'mastophiliac',
    # 'pareja-hub',
    # 'thiccivelvet',
    # 'like2fingers',
    # 'wetslavs',
    # 'wettmelons',
    # 'egg2025',
    # 'loadsonlucy',
    # 'that-tx-couple',
]


PORNSTARS = [
    # 'ashley-rosi',
    'lindsey-love',
]
